### PR TITLE
Fixes #78 on v2.0

### LINKED ISSUE #78: [BUG] client crash on guildMemberAdd when manage server permission isn't given
**Describe the bug**
Client crashes, when a user joins the server and the bot doesn't have the right to see the invites section (eg. manage server permission)

**Screenshots**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Vetrox**

### CODE REVIEW

File: modules/invite_manager/invite_manager.js [hunk 1]
```diff
@@ -103,6 +103,11 @@ function onGuildMemberAdd(member) {
 				log.logMessage(error);
 				log.logMessage(error.stack);
 			}
+		},
+		(reason) => {
+			bot.api.log.logMessage(
+				`Guild: ${member.guild.id} doesn't provide the required permission to fetch invites.`
```
Comment (roscha444) [inline modules/invite_manager/invite_manager.js]: maybe add $reason like in v1.0?

> Guild: ${member.guild.id} doesn't provide the required permission to fetch invites.\n ${reason}

Comment (Vetrox) [reply modules/invite_manager/invite_manager.js]: done.
